#!/bin/bash

 # Directorio del script actual
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Directorio que contiene los scripts a llamar (relativo al script actual)
SCRIPTS_DIR="$SCRIPT_DIR/utility_scripts"

backup_folder="$HOME/.RiceBackup"
backup_path="$backup_folder/${folder}_$date"


# Función para cargar un script y sus funciones
cargar_script() {
    local script_path="$SCRIPTS_DIR/$1"

    if [[ -f "$script_path" ]]; then
        source "$script_path"
    else
        echo "Error: El script '$1' no se encontró en $SCRIPTS_DIR"
        exit 1
    fi
}

check_gum() {
  if ! command -v gum &>/dev/null; then  # Verifica si gum NO está instalado
    if sudo pacman -S --noconfirm gum; then  # Intenta instalar con pacman
      color_echo -b -g "gum" -w "installed" -o "successfully"
    else
      echo "pacman -S gum FAILED" # Si falla, muestra un mensaje de error
    fi
  fi
}
# Cargar scripts necesarios (ajusta los nombres según tus scripts)
cargar_script "logo.sh"
cargar_script "colorsBashScript.sh"
cargar_script "menuPrincipal.sh"
s
# inicio del script


display_menu
logo "Welcome!"

main() {
    check_gum

    while :; do
        display_menu
        read -rp "Enter your choice: " CHOICE
        echo

         case $CHOICE in
;
            1)
            cargar_script "config_git"
            mantis ;
            q) clear && exit ;;
            *)
                gum style --foreground 50 "Invalid choice. Please select a valid option."
                echo
            ;;
        esac
        sleep 1
    done
}

 main
